#!/bin/sh

FILENAME="$HOME/.cache/corona"

inetcheck () { wget --quiet --spider https://google.com; }
download () { curl --silent https://corona-stats.online/GB > "$FILENAME"; }

# If the file doesn't exist or is more than 3600 seconds old, download the file again.
{
    [ -f "$FILENAME" ] &&
    [ -s "$FILENAME" ] &&
    [ $(($(date +%s)-$(stat -c %Y "$FILENAME"))) -lt 3600 ];
} || {
    inetcheck && download;
}

grep -E -i "UK" "$FILENAME" |
    sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" |
    sed "s/\s*//g ; s/║//g ; s/│/;/g ; s/▲//g" |
    awk -F';' '{print $3 " (😷"$8") (+"$4")", "💀" $5 " (+"$6")"}'

# Confirmed (3) (Active (8)) (+1 day change (6)) deaths (4) (+1 day deaths)

# Rank, Country, Total cases, new cases, total deaths, new deaths, recovered, active, critical, cases per million
# 1         2       3           4           5               6           7       8       9           10
